// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProtocolServiceClient is the client API for ProtocolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtocolServiceClient interface {
	// Run is function to start a protocol and return a stream to listen to
	// its progress.
	Run(ctx context.Context, in *Protocol, opts ...grpc.CallOption) (ProtocolService_RunClient, error)
	// Start asks the agency to start a protocol. It immediately returns a
	// protocol ID that allows to monitor the protocol with Status function.
	// When Agent service's Listen is in use, we get notifications how protocol
	// proceeds and when it's ready.
	Start(ctx context.Context, in *Protocol, opts ...grpc.CallOption) (*ProtocolID, error)
	// Status returns a current ProtocolStatus which offers both typed data fields
	// and combined JSON string.
	Status(ctx context.Context, in *ProtocolID, opts ...grpc.CallOption) (*ProtocolStatus, error)
	// Resume tells the protocol state machine how to proceed when it's waiting
	// user action e.g. permission to send response to proof request.
	Resume(ctx context.Context, in *ProtocolState, opts ...grpc.CallOption) (*ProtocolID, error)
	// Release releases the protocol state machine from agency. It can be called
	// only when protocol is in Ready state. After release you can access the
	// status information of your DIDComm with the others services of your system.
	Release(ctx context.Context, in *ProtocolID, opts ...grpc.CallOption) (*ProtocolID, error)
}

type protocolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtocolServiceClient(cc grpc.ClientConnInterface) ProtocolServiceClient {
	return &protocolServiceClient{cc}
}

func (c *protocolServiceClient) Run(ctx context.Context, in *Protocol, opts ...grpc.CallOption) (ProtocolService_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProtocolService_ServiceDesc.Streams[0], "/agency.v1.ProtocolService/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &protocolServiceRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProtocolService_RunClient interface {
	Recv() (*ProtocolState, error)
	grpc.ClientStream
}

type protocolServiceRunClient struct {
	grpc.ClientStream
}

func (x *protocolServiceRunClient) Recv() (*ProtocolState, error) {
	m := new(ProtocolState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *protocolServiceClient) Start(ctx context.Context, in *Protocol, opts ...grpc.CallOption) (*ProtocolID, error) {
	out := new(ProtocolID)
	err := c.cc.Invoke(ctx, "/agency.v1.ProtocolService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolServiceClient) Status(ctx context.Context, in *ProtocolID, opts ...grpc.CallOption) (*ProtocolStatus, error) {
	out := new(ProtocolStatus)
	err := c.cc.Invoke(ctx, "/agency.v1.ProtocolService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolServiceClient) Resume(ctx context.Context, in *ProtocolState, opts ...grpc.CallOption) (*ProtocolID, error) {
	out := new(ProtocolID)
	err := c.cc.Invoke(ctx, "/agency.v1.ProtocolService/Resume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolServiceClient) Release(ctx context.Context, in *ProtocolID, opts ...grpc.CallOption) (*ProtocolID, error) {
	out := new(ProtocolID)
	err := c.cc.Invoke(ctx, "/agency.v1.ProtocolService/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtocolServiceServer is the server API for ProtocolService service.
// All implementations must embed UnimplementedProtocolServiceServer
// for forward compatibility
type ProtocolServiceServer interface {
	// Run is function to start a protocol and return a stream to listen to
	// its progress.
	Run(*Protocol, ProtocolService_RunServer) error
	// Start asks the agency to start a protocol. It immediately returns a
	// protocol ID that allows to monitor the protocol with Status function.
	// When Agent service's Listen is in use, we get notifications how protocol
	// proceeds and when it's ready.
	Start(context.Context, *Protocol) (*ProtocolID, error)
	// Status returns a current ProtocolStatus which offers both typed data fields
	// and combined JSON string.
	Status(context.Context, *ProtocolID) (*ProtocolStatus, error)
	// Resume tells the protocol state machine how to proceed when it's waiting
	// user action e.g. permission to send response to proof request.
	Resume(context.Context, *ProtocolState) (*ProtocolID, error)
	// Release releases the protocol state machine from agency. It can be called
	// only when protocol is in Ready state. After release you can access the
	// status information of your DIDComm with the others services of your system.
	Release(context.Context, *ProtocolID) (*ProtocolID, error)
	mustEmbedUnimplementedProtocolServiceServer()
}

// UnimplementedProtocolServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProtocolServiceServer struct {
}

func (UnimplementedProtocolServiceServer) Run(*Protocol, ProtocolService_RunServer) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedProtocolServiceServer) Start(context.Context, *Protocol) (*ProtocolID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedProtocolServiceServer) Status(context.Context, *ProtocolID) (*ProtocolStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedProtocolServiceServer) Resume(context.Context, *ProtocolState) (*ProtocolID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedProtocolServiceServer) Release(context.Context, *ProtocolID) (*ProtocolID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedProtocolServiceServer) mustEmbedUnimplementedProtocolServiceServer() {}

// UnsafeProtocolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtocolServiceServer will
// result in compilation errors.
type UnsafeProtocolServiceServer interface {
	mustEmbedUnimplementedProtocolServiceServer()
}

func RegisterProtocolServiceServer(s grpc.ServiceRegistrar, srv ProtocolServiceServer) {
	s.RegisterService(&ProtocolService_ServiceDesc, srv)
}

func _ProtocolService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Protocol)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProtocolServiceServer).Run(m, &protocolServiceRunServer{stream})
}

type ProtocolService_RunServer interface {
	Send(*ProtocolState) error
	grpc.ServerStream
}

type protocolServiceRunServer struct {
	grpc.ServerStream
}

func (x *protocolServiceRunServer) Send(m *ProtocolState) error {
	return x.ServerStream.SendMsg(m)
}

func _ProtocolService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Protocol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.v1.ProtocolService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolServiceServer).Start(ctx, req.(*Protocol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocolID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.v1.ProtocolService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolServiceServer).Status(ctx, req.(*ProtocolID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocolState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.v1.ProtocolService/Resume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolServiceServer).Resume(ctx, req.(*ProtocolState))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocolID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.v1.ProtocolService/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolServiceServer).Release(ctx, req.(*ProtocolID))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtocolService_ServiceDesc is the grpc.ServiceDesc for ProtocolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtocolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agency.v1.ProtocolService",
	HandlerType: (*ProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _ProtocolService_Start_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ProtocolService_Status_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _ProtocolService_Resume_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _ProtocolService_Release_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _ProtocolService_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol.proto",
}
