FROM golang:1.20-buster AS s3-builder

WORKDIR /work

COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -o /go/bin/s3-copy

FROM ghcr.io/findy-network/findy-agent-infra/indy-base:indy-1.16.ubuntu-18.04

COPY --from=s3-builder /go/bin/s3-copy /s3-copy
RUN chmod a+x /s3-copy
