FROM golang:1.20-alpine3.17

WORKDIR /work

COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -o /go/bin/s3-copy

FROM alpine:3.15

COPY --from=0 /go/bin/s3-copy /s3-copy

RUN chmod a+x /s3-copy

