name: tag-release
on:
  schedule:
    - cron: "0 1 * * 1-5" # run at 1 AM UTC on weekdays
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag release if changes
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.AGENCY_RELEASER_ID }}
          private-key: ${{ secrets.AGENCY_RELEASER_KEY }}
      - uses: findy-network/releaser-action@master
        with:
          token: ${{ steps.generate_token.outputs.token }}
          gate: test
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
